version: '3'

networks:
  main-network:

services:
  mssql:
    image: metaskills/mssql-server-linux-tinytds:2017-GA
    container_name: sqlserver
    ports:
      - "1433:1433"
    networks:
      - main-network

  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "1234:1234"
    networks:
      - main-network

  cimgruby:
    image: cimg/ruby:2.7.0
    environment:
      TESTOPTS: "-v"
      TINYTDS_UNIT_DATASERVER: sqlserver
      TINYTDS_UNIT_HOST: sqlserver
      SA_PASSWORD: super01S3cUr3
      TOXIPROXY_HOST: toxiproxy.tiny_tds_main-network
    command: tail -F anything
    volumes:
      - .:/home/circleci/repo
    networks:
      - main-network