version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  test_linux:
    parameters:
      ruby_version:
        description: 'version tag for the cimg/ruby container'
        type: string

    docker:
      # Primary container image where all commands run
      - image: cimg/ruby:<< parameters.ruby_version >>
        environment:
          TESTOPTS: '-v'
          TINYTDS_UNIT_DATASERVER: sqlserver
          TINYTDS_UNIT_HOST: sqlserver
          SA_PASSWORD: super01S3cUr3
          TOXIPROXY_HOST: toxiproxy

      # Service container image
      - image: mcr.microsoft.com/mssql/server:2019-latest
        name: sqlserver
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: super01S3cUr3

      # tests based on toxiproxy are broken, last working on
      # v2.1.4 (2019). This is pinned to the closest older
      # version until those tests can be fixed
      - image: ghcr.io/shopify/toxiproxy:2.1.5
        name: toxiproxy

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install sql prereqs
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
            sudo apt-get update
            sudo ACCEPT_EULA=Y apt-get -y install mssql-tools unixodbc-dev

      - run:
          name: setup tiny_tds test database
          command: |
            /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P $SA_PASSWORD -i ./test/sql/db-create.sql
            /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P $SA_PASSWORD -i ./test/sql/db-login.sql

      - run:
          name: compile openssl library
          command: |
            sudo ./test/bin/install-openssl.sh

      - run:
          name: compile freetds library
          command: |
            sudo ./test/bin/install-freetds.sh

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: bundle install gems
          command: |
            bundle install

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          name: build gem
          command: |
            bundle exec rake build

      - run:
          name: test gem
          command: |
            bundle exec rake test

  test_windows:
    parameters:
      ruby_version:
        description: 'version tag for rubydev environment'
        type: string

    executor:
      name: win/server-2022
      shell: powershell.exe

    environment:
      RAKEOPT: '-rdevkit'
      TESTOPTS: '-v'
      MAKE: 'make V=1 -j2'

    steps:
      - run:
          name: remove pre-installed ruby
          command: |
            Get-ChildItem -path 'C:\tools\' -filter Ruby* | Remove-Item -Force -Recurse

      - run:
          name: download and install ruby devkit
          command: |
            $uri = 'https://api.github.com/repos/oneclick/rubyinstaller2/tags?per_page=200'
            $releases = ((Invoke-WebRequest $uri) | ConvertFrom-Json).name | select-string -Pattern '<< parameters.ruby_version >>'
            $target_release = (($releases | Sort-Object -Descending)[0] | Out-String).Trim()
            $target_version = $target_release.Substring($target_release.Length - 7)
            $download_uri = "https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-$target_version/rubyinstaller-devkit-$target_version-x64.exe"
            echo "Ruby Target Version Found: $target_version"

            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
            Invoke-WebRequest -UseBasicParsing -uri $download_uri -OutFile ruby-setup.exe;
            .\ruby-setup.exe /VERYSILENT /NORESTART /DIR=C:/Ruby<< parameters.ruby_version >>-x64;

      - run:
          name: ruby diagnostics
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            echo "Perl Version:"
            perl --version
            echo "Ruby Version:"
            ruby --version
            echo "Gem Version:"
            gem --version
            rm .\ruby-setup.exe

      - run:
          name: update build env
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            ridk install 2
            gem install bundler

      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: bundle install gems
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            bundle install

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          name: build openssl
          no_output_timeout: 30m
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            bundle exec rake ports:openssl

      - run:
          name: build libiconv
          no_output_timeout: 30m
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            bundle exec rake ports:libiconv

      - run:
          name: build freetds
          no_output_timeout: 30m
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            bundle exec rake ports:freetds

      - run:
          name: build gem
          no_output_timeout: 30m
          command: |
            $Env:PATH = "C:\\Ruby<< parameters.ruby_version >>-x64\\bin;$Env:PATH"
            bundle exec rake ports

workflows:
  test_supported_ruby_versions:
    jobs:
      - test_linux:
          matrix:
            parameters:
              ruby_version:
                - '2.5'
                - '2.6'
                - '2.7'

      - test_windows:
          matrix:
            parameters:
              ruby_version:
               - '2.5'
               - '2.6'
               - '2.7'
